// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXT-vK9b7tooA8hCbYeMVAv-Hz2I5Fvx0',
    appId: '1:746522585271:web:04ed2d5808201a213a8532',
    messagingSenderId: '746522585271',
    projectId: 'waru-bora-test',
    authDomain: 'waru-bora-test.firebaseapp.com',
    storageBucket: 'waru-bora-test.appspot.com',
    measurementId: 'G-NC67KVV7LY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCO-KPXxI7OqLcis8CNAhME7BoRMz40HY',
    appId: '1:746522585271:android:cc7b6aa152ea931f3a8532',
    messagingSenderId: '746522585271',
    projectId: 'waru-bora-test',
    storageBucket: 'waru-bora-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0b153XZn3cRzCUYVaPmXMSAdWTcsOScE',
    appId: '1:746522585271:ios:46cfc8c7c9e1c3a53a8532',
    messagingSenderId: '746522585271',
    projectId: 'waru-bora-test',
    storageBucket: 'waru-bora-test.appspot.com',
    iosClientId:
        '746522585271-eugj6bflekgtmlenag0ogq9es43vc7hf.apps.googleusercontent.com',
    iosBundleId: 'com.example.waruBoraTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0b153XZn3cRzCUYVaPmXMSAdWTcsOScE',
    appId: '1:746522585271:ios:46cfc8c7c9e1c3a53a8532',
    messagingSenderId: '746522585271',
    projectId: 'waru-bora-test',
    storageBucket: 'waru-bora-test.appspot.com',
    iosClientId:
        '746522585271-eugj6bflekgtmlenag0ogq9es43vc7hf.apps.googleusercontent.com',
    iosBundleId: 'com.example.waruBoraTest',
  );
}
